Name - Ankit
Roll No.-19MTS5630
Class-BSc Mathematical Science 2nd year(3rd sem)
Date-07 Sept 2020

In [ ]:
import pandas as pd
from pandas import Series, DataFrame


1. Create a Series of 10 elements and change their default index from numeric to alphabets starting from 'a'.

In [ ]:
sdata=np.arange(10)
obj=pd.Series(sdata)
obj

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
obj.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
obj.reindex=['a', 'b', 'c', 'd', 'e','f','g','h','i','j']
obj

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

2. Create a series of the following batting averages with batsmen name as the key. Name the index as Batsmen and value as Batting Average.
(Rohit: 152, Shikhar: 102, Virat: 170, Shreyas: 95, Rishabh: 125, Hardik: 112, Ravindra: 88, Bhuvaneshwar: 75, Kuldeep: 67, Shami: 59, Bumrah: 12)
Perform the following operations on the Series created.


In [ ]:
data={'Rohit' : 152, 'Shikhar' : 102, 'Virat': 170, 'Shreyas': 95, 'Rishabh':125, 'Hardik':112, 'Ravindra': 88, 'Bhuvaneshwar': 75, 'Kuldeep':67, 'Shami':59, 'Bumrah':12}
batdata=pd.Series(data)
batdata.index.name="Batsmen"
batdata.name="Batting Average"
batdata 


Batsmen
Rohit           152
Shikhar         102
Virat           170
Shreyas          95
Rishabh         125
Hardik          112
Ravindra         88
Bhuvaneshwar     75
Kuldeep          67
Shami            59
Bumrah           12
Name: Batting Average, dtype: int64

(a) Display the list of Batsmen with more than 100 as batting average


In [ ]:
batdata[batdata>100]

Batsmen
Rohit      152
Shikhar    102
Virat      170
Rishabh    125
Hardik     112
Name: Batting Average, dtype: int64

(b) Display the list of Batsmen with less than 90 as batting average


In [ ]:
batdata[batdata<90]

Batsmen
Ravindra        88
Bhuvaneshwar    75
Kuldeep         67
Shami           59
Bumrah          12
Name: Batting Average, dtype: int64

(c) Due to the good performance of the top six batsmen, increase their average by 25%


In [ ]:
batdata.head(6)*1.25



Batsmen
Rohit      190.00
Shikhar    127.50
Virat      212.50
Shreyas    118.75
Rishabh    156.25
Hardik     140.00
Name: Batting Average, dtype: float64

(d) Due to the poor performance of the bottom three batsmen, decrease their average by 10%


In [ ]:
batdata.tail(3)*0.9


Batsmen
Kuldeep    60.3
Shami      53.1
Bumrah     10.8
Name: Batting Average, dtype: float64

(e) Include a 12th man named 'Chahal' in the list without any batting average and display the new list


In [ ]:
batdata=batdata.reindex(['Rohit','Shikhar','Virat','Shreyas','Rishabh','Hardik','Ravindra','Bhuvaneshwar','Kuldeep','Shami','Bumrah','Chahal'])
batdata

Batsmen
Rohit           152.0
Shikhar         102.0
Virat           170.0
Shreyas          95.0
Rishabh         125.0
Hardik          112.0
Ravindra         88.0
Bhuvaneshwar     75.0
Kuldeep          67.0
Shami            59.0
Bumrah           12.0
Chahal            NaN
Name: Batting Average, dtype: float64

(f) Display how many batting averages are NULL in the list


In [ ]:
batdata.isnull()

Batsmen
Rohit           False
Shikhar         False
Virat           False
Shreyas         False
Rishabh         False
Hardik          False
Ravindra        False
Bhuvaneshwar    False
Kuldeep         False
Shami           False
Bumrah          False
Chahal           True
Name: Batting Average, dtype: bool

(g) Display how many batting averages are NOT NULL in the list 


In [ ]:
batdata.notnull()

Batsmen
Rohit            True
Shikhar          True
Virat            True
Shreyas          True
Rishabh          True
Hardik           True
Ravindra         True
Bhuvaneshwar     True
Kuldeep          True
Shami            True
Bumrah           True
Chahal          False
Name: Batting Average, dtype: bool

(h) Due to injury to Shikhar, he was replaced by "Rahul" having a batting average of 120. Change that in the series and display the new series.

In [ ]:

batdata.index=['Rohit', 'Rahul', 'Virat', 'Shreyas', 'Rishabh', 'Hardik', 'Ravindra',
       'Bhuvaneshwar', 'Kuldeep', 'Shami', 'Bumrah','Chahal']
batdata['Rahul']=120
batdata

Rohit           152.0
Rahul           120.0
Virat           170.0
Shreyas          95.0
Rishabh         125.0
Hardik          112.0
Ravindra         88.0
Bhuvaneshwar     75.0
Kuldeep          67.0
Shami            59.0
Bumrah           12.0
Chahal            NaN
Name: Batting Average, dtype: float64

3. Create another series of bowling average of the same team having the following averages.
(Rohit: 102, Shikhar: 100, Virat: 121, Shreyas: 112, Rishabh: 100, Hardik: 42, Ravindra: 41, Bhuvaneshwar: 32, Kuldeep: 36, Shami: 27, Bumrah: 19)

In [ ]:
data2={'Rohit': 102, 'Shikhar': 100, 'Virat': 121, 'Shreyas': 112, 'Rishabh': 100, 'Hardik': 42, 'Ravindra': 41, 'Bhuvaneshwar': 32, 'Kuldeep': 36, 'Shami': 27, 'Bumrah': 19}
boldata=pd.Series(data2)
boldata

Rohit           102
Shikhar         100
Virat           121
Shreyas         112
Rishabh         100
Hardik           42
Ravindra         41
Bhuvaneshwar     32
Kuldeep          36
Shami            27
Bumrah           19
dtype: int64

(a) Find out the ratio of the batting/bowling average for the two series

In [ ]:
batdata/boldata

Bhuvaneshwar    2.343750
Bumrah          0.631579
Chahal               NaN
Hardik          2.666667
Kuldeep         1.861111
Rahul                NaN
Ravindra        2.146341
Rishabh         1.250000
Rohit           1.490196
Shami           2.185185
Shikhar              NaN
Shreyas         0.848214
Virat           1.404959
dtype: float64

(b) Find out the difference of the batting & bowling average for the two series


In [ ]:
batdata-boldata

Bhuvaneshwar    43.0
Bumrah          -7.0
Chahal           NaN
Hardik          70.0
Kuldeep         31.0
Rahul            NaN
Ravindra        47.0
Rishabh         25.0
Rohit           50.0
Shami           32.0
Shikhar          NaN
Shreyas        -17.0
Virat           49.0
dtype: float64

(c) Display the players having the ratio of the two averages of more than 1.5

In [ ]:
batdata/boldata>1.5

Bhuvaneshwar     True
Bumrah          False
Chahal          False
Hardik           True
Kuldeep          True
Rahul           False
Ravindra         True
Rishabh         False
Rohit           False
Shami            True
Shikhar         False
Shreyas         False
Virat           False
dtype: bool

4. Create a dataframe of 10 students for their complete graduation (3 years) with 3 columns - Name, Year, Percentage 
e.g. (Ram, 2017, 75), (Ram, 2018, 77), (Ram, 2019, 80), (Reeta, 2017, 83), (Reeta, 2018, 89), (Reeta, 2019, 85), etc. (This will make 30 entries in the dataframe for the 10 students across 3 years [2017-2018-2019])
Perform the following operations.


In [ ]:
rdata={'Name':['Ram','Ram','Ram','Shyam','Shyam','Shyam','Jake','Jake','Jake','Fake','Fake','Fake','Gina','Gina','Gina','Tina','Tina','Tina','Menna','Menna','Menna','Sam','Sam','Sam','Mike','Mike','Mike','Harvey','Harvey','Harvey'],'Year':[2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019,2017,2018,2019],'Percentage':[75,45,68,83,42,54,98,76,67,67,44,33,98,60,75,45,76,69,70,78,89,87,96,69,80,78,75,65,67,87]}
record=pd.DataFrame(rdata)
record

Name  Year  Percentage
0      Ram  2017          75
1      Ram  2018          45
2      Ram  2019          68
3    Shyam  2017          83
4    Shyam  2018          42
5    Shyam  2019          54
6     Jake  2017          98
7     Jake  2018          76
8     Jake  2019          67
9     Fake  2017          67
10    Fake  2018          44
11    Fake  2019          33
12    Gina  2017          98
13    Gina  2018          60
14    Gina  2019          75
15    Tina  2017          45
16    Tina  2018          76
17    Tina  2019          69
18   Menna  2017          70
19   Menna  2018          78
20   Menna  2019          89
21     Sam  2017          87
22     Sam  2018          96
23     Sam  2019          69
24    Mike  2017          80
25    Mike  2018          78
26    Mike  2019          75
27  Harvey  2017          65
28  Harvey  2018          67
29  Harvey  2019          87

(a) Display the first 8 entries of the dataframe


In [ ]:
record.head(8)

Name  Year  Percentage
0    Ram  2017          75
1    Ram  2018          45
2    Ram  2019          68
3  Shyam  2017          83
4  Shyam  2018          42
5  Shyam  2019          54
6   Jake  2017          98
7   Jake  2018          76

(b) Display the last 5 entries of the dataframe


In [ ]:
record.tail()

Name  Year  Percentage
25    Mike  2018          78
26    Mike  2019          75
27  Harvey  2017          65
28  Harvey  2018          67
29  Harvey  2019          87

(c) Change the index values of the dataframe with numbers written as text. e.g. 1 replaced as One, 2 replaced as Two, etc.


In [ ]:
record.index=['zero','one', 'two', 'three', 'four','five', 'six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty','twentyone','twentytwo','twentythree','twentyfour','twentyfive','twentysix','twentyseven','twentyeight','twentynine']
record

Name  Year  Percentage
zero            Ram  2017          75
one             Ram  2018          45
two             Ram  2019          68
three         Shyam  2017          83
four          Shyam  2018          42
five          Shyam  2019          54
six            Jake  2017          98
seven          Jake  2018          76
eight          Jake  2019          67
nine           Fake  2017          67
ten            Fake  2018          44
eleven         Fake  2019          33
twelve         Gina  2017          98
thirteen       Gina  2018          60
fourteen       Gina  2019          75
fifteen        Tina  2017          45
sixteen        Tina  2018          76
seventeen      Tina  2019          69
eighteen      Menna  2017          70
nineteen      Menna  2018          78
twenty        Menna  2019          89
twentyone       Sam  2017          87
twentytwo       Sam  2018          96
twentythree     Sam  2019          69
twentyfour     Mike  2017          80
twentyfive     Mike  2018          78
twentysix      Mike  2019          75
twentyseven  Harvey  2017          65
twentyeight  Harvey  2018          67
twentynine   Harvey  2019          87

(d) Add a grade column with no values


In [ ]:
record = pd.DataFrame(rdata, columns=['Name', 'Year', 'Percentage', 'Grade'])
record

Name  Year  Percentage Grade
0      Ram  2017          75   NaN
1      Ram  2018          45   NaN
2      Ram  2019          68   NaN
3    Shyam  2017          83   NaN
4    Shyam  2018          42   NaN
5    Shyam  2019          54   NaN
6     Jake  2017          98   NaN
7     Jake  2018          76   NaN
8     Jake  2019          67   NaN
9     Fake  2017          67   NaN
10    Fake  2018          44   NaN
11    Fake  2019          33   NaN
12    Gina  2017          98   NaN
13    Gina  2018          60   NaN
14    Gina  2019          75   NaN
15    Tina  2017          45   NaN
16    Tina  2018          76   NaN
17    Tina  2019          69   NaN
18   Menna  2017          70   NaN
19   Menna  2018          78   NaN
20   Menna  2019          89   NaN
21     Sam  2017          87   NaN
22     Sam  2018          96   NaN
23     Sam  2019          69   NaN
24    Mike  2017          80   NaN
25    Mike  2018          78   NaN
26    Mike  2019          75   NaN
27  Harvey  2017          65   NaN
28  Harvey  2018          67   NaN
29  Harvey  2019          87   NaN

(e) Display the student details only for the year 2018


In [ ]:
record[record['Year']==2018]

Name  Year  Percentage Grade
1      Ram  2018          45   NaN
4    Shyam  2018          42   NaN
7     Jake  2018          76   NaN
10    Fake  2018          44   NaN
13    Gina  2018          60   NaN
16    Tina  2018          76   NaN
19   Menna  2018          78   NaN
22     Sam  2018          96   NaN
25    Mike  2018          78   NaN
28  Harvey  2018          67   NaN

(f) Display the student details having more than 75% marks in any year


In [ ]:
record[record.Percentage>75]

Name  Year  Percentage Grade
3    Shyam  2017          83   NaN
6     Jake  2017          98   NaN
7     Jake  2018          76   NaN
12    Gina  2017          98   NaN
16    Tina  2018          76   NaN
19   Menna  2018          78   NaN
20   Menna  2019          89   NaN
21     Sam  2017          87   NaN
22     Sam  2018          96   NaN
24    Mike  2017          80   NaN
25    Mike  2018          78   NaN
29  Harvey  2019          87   NaN

(g) Find the transpose of the dataframe

In [ ]:
record.T


0     1     2      3      4   ...    25    26      27      28      29
Name         Ram   Ram   Ram  Shyam  Shyam  ...  Mike  Mike  Harvey  Harvey  Harvey
Year        2017  2018  2019   2017   2018  ...  2018  2019    2017    2018    2019
Percentage    75    45    68     83     42  ...    78    75      65      67      87
Grade        NaN   NaN   NaN    NaN    NaN  ...   NaN   NaN     NaN     NaN     NaN

[4 rows x 30 columns]